### ISSUE TITLE
Bare Metal Raspberry Pi - Will circle development work for  Raspberry pi zero target & boot speed

### ISSUE THREAD

**Issue by aniljgupta** [rsta2/circle-docs#1]
I am to use **Raspberry pi zero for some Embedded graphics application .

My question is

(1)  Will circle application development framework  output work  for  Raspberry pi zero as  target ?
or alternatively can  we choose processor / board target  as Raspberry pi zero*
 (2) **Boot speed of system / application** ie in how much time target application will start after power on the system?

**Comment by rsta2** [comment]
Yes, Circle can be used to develop applications for the Raspberry Pi Zero. The 
RPi Zero has the same SoC like the RPi 1, so you have to set in your Config.mk 
file:

RASPPI = 1

Starting goes quite quick. I would say, I takes 2 seconds before your app gets 
control.

**Comment by aniljgupta** [comment]
Thanks a lot for your answer & guide. Circle is excellent development framework / platform for  bare metal raspberry programming particular embedded system. Even optimised  Linux kernel take around 1-2 minutes to boot & that make it very less attractive for real time embedded system. I have heard some linux distro booting in 2 sec but not found it anywhere. Linux comes with lots of components / modules that are not at all required in normal embedded system. And these conserve system resources like memory & CPU time . Thanks a lot for reply & help

**Comment by rsta2** [comment]
You are welcome. Thanks for appreciating Circle!

**Comment by aniljgupta** [comment]
okOnce again thanks for your help
Anil Gupta
    On Tuesday, June 4, 2024 at 03:52:59 PM GMT+5:30, Rene Stange ***@***.***> wrote:  
 
 


Closed #1 as completed.
